# Stochastic Gradient Descent - Linear Regression

## Data for the linear regression model

In [ ]:
import numpy as np

In [ ]:
# Data points
data_amount = 15
max_num = 10
X = np.random.randint(max_num, size=(data_amount, 3))

# We generate them by "knowing" the output weights for this example (this is not the case for real data!)
final_weights = np.random.rand(X.shape[1])
final_weights = final_weights / np.sum(final_weights)

final_bias = 0.2

# Corresponding labels
random_noise = np.random.rand(X.shape[0]) / 7.5 # ranges from 0-1. We divide that by 7.5 to not get to much noise in here
y = np.dot(final_weights, X.T) + final_bias + random_noise

print('data set X\n', X)
print('labels y\n', y)

data set X
 [[8 9 9]
 [2 3 2]
 [8 8 6]
 [9 3 9]
 [0 5 4]
 [0 2 4]
 [5 9 7]
 [6 2 9]
 [7 7 9]
 [5 7 4]
 [6 8 6]
 [2 4 8]
 [3 4 8]
 [3 9 2]
 [3 9 7]]
labels y
 [8.91704529 2.55446801 7.53632159 7.51019882 3.24059182 2.32726007
 7.18196219 6.20066083 8.03408955 5.51227843 6.81990819 5.06873828
 5.45261472 4.7353377  6.49525448]


# Training and test data

In [ ]:
train_len = int(data_amount * 0.75)

# We train with the following data
X_train = X[:train_len]
y_train = y[:train_len]

# We test / evaluate with the following data
X_test = X[train_len:]
y_test = y[train_len:]

## Information about the model

In [ ]:
# We set the inital weights randomly
weights = np.random.rand(X.shape[1])

# The bias value is set to 1 initially
bias = np.array([1])

### Some more information

We know the regression equation:

$y_{pred}= w_1x_1 + w_2x_2 + \ldots + w_nx_n + b$

In [ ]:
# What are the current results of the untrained model?
y_untrained = np.dot(weights, X_test.T) + bias
print('Outputs for our untrained model:', y_untrained)

# What are the results of the final model (that we want to achieve by updating the weights by the Stochastic gradient descent method)
y_final = np.dot(final_weights, X_test.T) + final_bias
print('Outputs for the final model:', y_final)

Outputs for our untrained model: [ 7.62280808  8.54052987 10.17773166 11.53617037]
Outputs for the final model: [5.02264467 5.35307751 4.62125981 6.47564776]


### Loss function

We want to use the mean squarred error to calculate the loss for the model outputs which is defined as follows:

$$MSE = \frac{1}{n}\sum_{i=1}^n (y_i-y_{i_{pred}})^2$$

In [ ]:
mse = lambda y, y_pred: np.mean(np.sum((y-y_pred)**2))

In [ ]:
# In our example the loss for our untrained model is:
loss_untrained = mse(y_test, y_untrained)
print('The loss of the untrained model is:', loss_untrained)

# Loss for the final model
loss_final = mse(y_test, y_final)
print('The loss of the final model is:', loss_final)

The loss of the untrained model is: 71.08897746770502
The loss of the final model is: 0.02543046423054612


## Your stochastic gradient descent implementation to optimize the weights of your model

In [ ]:
# Summary on what we know so far:

# We know the loss function: Variable 'mse' (Mean squared error)
# We know the initial weights that we want to optimize: variable 'weights'
# We know the initial bias value: variable 'bias'

In [ ]:
# Use the training data to optimize the weights of the linear regression model

# Data points
data_amount = 15
max_num = 10
X = np.random.randint(max_num, size=(data_amount, 3))

# We generate them by "knowing" the output weights for this example (this is not the case for real data!)
final_weights = np.random.rand(X.shape[1])
final_weights = final_weights / np.sum(final_weights)

final_bias = 0.2

# Corresponding labels
random_noise = np.random.rand(X.shape[0]) / 7.5 # ranges from 0-1. We divide that by 7.5 to not get to much noise in here
y = np.dot(final_weights, X.T) + final_bias + random_noise

train_len = int(data_amount * 0.75)

# We train with the following data
X_train = X[:train_len]
y_train = y[:train_len]

# We test / evaluate with the following data
X_test = X[train_len:]
y_test = y[train_len:]


# use these variables for your sgd implementation
# We set the inital weights randomly
weights = np.random.rand(X.shape[1])

# The bias value is set to 1 initially
bias = np.array([1])
# What are the current results of the untrained model?
y_untrained = np.dot(weights, X_test.T) + bias
# print('Outputs for our untrained model:', y_untrained)

# What are the results of the final model (that we want to achieve by updating the weights by the Stochastic gradient descent method)
y_final = np.dot(final_weights, X_test.T) + final_bias
# print('Outputs for the final model:', y_final)
mse = lambda y, y_pred: np.mean(np.sum((y-y_pred)**2))

# In our example the loss for our untrained model is:
loss_untrained = mse(y_test, y_untrained)
# print('The loss of the untrained model is:', loss_untrained)

# Loss for the final model
loss_final = mse(y_test, y_final)
# print('The loss of the final model is:', loss_final)

learning_rate = 0.005
iterations = 1000

# SGD Algorithm
for epoch in range(iterations):
    for i in range(X.shape[0]):
        # Calculate the prediction
        y_pred = np.dot(X[i], weights) + bias
        # Calculate the error
        error = y_pred - y[i]
        # Update weights and bias
        weights -= learning_rate * error * X[i]
        bias = bias - learning_rate * error
print("Weights:", weights)
print("Bias:", bias)


Weights: [0.43507394 0.11299895 0.46047273]
Bias: [0.24105984]
